# Generated by Django 4.1 on 2023-08-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='order_id',
        ),
    ]
