# Generated by Django 4.1 on 2023-08-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField()),
                ('is_seller', models.BooleanField()),
                ('phone', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.ordermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
